### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Gadgetoid** [UnfinishedStuff/Pimoroni_Pico_Display_Pack_documentation#1]
First off... this is incredible stuff.

If I might venture a suggestion or two:
1. Use more depths of heading
2. If you use VSCode grab the Markdown: All In One plugin, stick your cursor somewhere table-of-contents-ey and go "Ctrl+Shift+P" and type "table of" and pick "Markdown All In One: Create Table of Contents"
3. Use the `python` syntax highlighting for backticks, ie

```python
# Boilerplate code which will be needed for any program using the Pimoroni Display Pack

# Import the module containing the display code
import picodisplay as display

# Get the width of the display, in pixels
width = display.get_width()
# Get the height of the display, in pixels
height = display.get_height()
```

which is done by putting the word "python" right after the three starting backticks

4. Don't ever stop :laughing:

**Comment by UnfinishedStuff** [comment]
Thanks @Gadgetoid.  I use Github pretty infrequently and didn't know about the python syntax highlighting, that's a great tip.  Depending on free time I'll keep working away on it and like I said on Twitter, bash out something more appropriate for the Pimoroni repo.

**Comment by scott-pett** [comment]
Many thanks UnfinishedStuff. I received my Pico and was struggling with it until I found your link.
Keep going.
Cheers,
Scott

**Comment by UnfinishedStuff** [comment]
Thanks for the feedback everyone, it has been very useful, and I'm glad you're finding the docs useful!  I think I've incorporated the guts of the feedback so I'm going to close this, but feel free to open a new issue if there's something you feel is missing.
