### ISSUE TITLE
Display.flip()

### ISSUE THREAD

**Issue by jkuss** [UnfinishedStuff/Pimoroni_Pico_Display_Pack_documentation#6]
Display.flip() now exists. It appears to take no parameters and rotates the screen 180º

**Comment by UnfinishedStuff** [comment]
Thanks for pointing that out. Honestly, I've not touched this (or any) repo in an age, because life and work have gotten in the way. I'll try to find time to update it with your suggestion soon (I'm away without a laptop at the moment), but no promises. I hope you've found it useful anyway.

**Comment by UnfinishedStuff** [comment]
Resolved by the merge of #7 , thanks jkuss!
